/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as DataRouteRouteImport } from './routes/data/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FactoriesIndexRouteImport } from './routes/factories.index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as FactoriesFactoryIdRouteImport } from './routes/factories.$factoryId'
import { Route as DataSchematicsIndexRouteImport } from './routes/data/schematics.index'
import { Route as DataRecipesIndexRouteImport } from './routes/data/recipes.index'
import { Route as DataItemsIndexRouteImport } from './routes/data/items.index'
import { Route as DataBuildingsIndexRouteImport } from './routes/data/buildings.index'
import { Route as DataBuildablesIndexRouteImport } from './routes/data/buildables.index'
import { Route as DataSchematicsSlugRouteImport } from './routes/data/schematics.$slug'
import { Route as DataRecipesSlugRouteImport } from './routes/data/recipes.$slug'
import { Route as DataItemsSlugRouteImport } from './routes/data/items.$slug'
import { Route as DataBuildingsSlugRouteImport } from './routes/data/buildings.$slug'
import { Route as DataBuildablesSlugRouteImport } from './routes/data/buildables.$slug'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRouteRoute = DataRouteRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoriesIndexRoute = FactoriesIndexRouteImport.update({
  id: '/factories/',
  path: '/factories/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataRouteRoute,
} as any)
const FactoriesFactoryIdRoute = FactoriesFactoryIdRouteImport.update({
  id: '/factories/$factoryId',
  path: '/factories/$factoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSchematicsIndexRoute = DataSchematicsIndexRouteImport.update({
  id: '/schematics/',
  path: '/schematics/',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataRecipesIndexRoute = DataRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataItemsIndexRoute = DataItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataBuildingsIndexRoute = DataBuildingsIndexRouteImport.update({
  id: '/buildings/',
  path: '/buildings/',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataBuildablesIndexRoute = DataBuildablesIndexRouteImport.update({
  id: '/buildables/',
  path: '/buildables/',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataSchematicsSlugRoute = DataSchematicsSlugRouteImport.update({
  id: '/schematics/$slug',
  path: '/schematics/$slug',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataRecipesSlugRoute = DataRecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataItemsSlugRoute = DataItemsSlugRouteImport.update({
  id: '/items/$slug',
  path: '/items/$slug',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataBuildingsSlugRoute = DataBuildingsSlugRouteImport.update({
  id: '/buildings/$slug',
  path: '/buildings/$slug',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataBuildablesSlugRoute = DataBuildablesSlugRouteImport.update({
  id: '/buildables/$slug',
  path: '/buildables/$slug',
  getParentRoute: () => DataRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRouteRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/logistics': typeof LogisticsRoute
  '/map': typeof MapRoute
  '/factories/$factoryId': typeof FactoriesFactoryIdRoute
  '/data/': typeof DataIndexRoute
  '/factories/': typeof FactoriesIndexRoute
  '/data/buildables/$slug': typeof DataBuildablesSlugRoute
  '/data/buildings/$slug': typeof DataBuildingsSlugRoute
  '/data/items/$slug': typeof DataItemsSlugRoute
  '/data/recipes/$slug': typeof DataRecipesSlugRoute
  '/data/schematics/$slug': typeof DataSchematicsSlugRoute
  '/data/buildables/': typeof DataBuildablesIndexRoute
  '/data/buildings/': typeof DataBuildingsIndexRoute
  '/data/items/': typeof DataItemsIndexRoute
  '/data/recipes/': typeof DataRecipesIndexRoute
  '/data/schematics/': typeof DataSchematicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/logistics': typeof LogisticsRoute
  '/map': typeof MapRoute
  '/factories/$factoryId': typeof FactoriesFactoryIdRoute
  '/data': typeof DataIndexRoute
  '/factories': typeof FactoriesIndexRoute
  '/data/buildables/$slug': typeof DataBuildablesSlugRoute
  '/data/buildings/$slug': typeof DataBuildingsSlugRoute
  '/data/items/$slug': typeof DataItemsSlugRoute
  '/data/recipes/$slug': typeof DataRecipesSlugRoute
  '/data/schematics/$slug': typeof DataSchematicsSlugRoute
  '/data/buildables': typeof DataBuildablesIndexRoute
  '/data/buildings': typeof DataBuildingsIndexRoute
  '/data/items': typeof DataItemsIndexRoute
  '/data/recipes': typeof DataRecipesIndexRoute
  '/data/schematics': typeof DataSchematicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRouteRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/logistics': typeof LogisticsRoute
  '/map': typeof MapRoute
  '/factories/$factoryId': typeof FactoriesFactoryIdRoute
  '/data/': typeof DataIndexRoute
  '/factories/': typeof FactoriesIndexRoute
  '/data/buildables/$slug': typeof DataBuildablesSlugRoute
  '/data/buildings/$slug': typeof DataBuildingsSlugRoute
  '/data/items/$slug': typeof DataItemsSlugRoute
  '/data/recipes/$slug': typeof DataRecipesSlugRoute
  '/data/schematics/$slug': typeof DataSchematicsSlugRoute
  '/data/buildables/': typeof DataBuildablesIndexRoute
  '/data/buildings/': typeof DataBuildingsIndexRoute
  '/data/items/': typeof DataItemsIndexRoute
  '/data/recipes/': typeof DataRecipesIndexRoute
  '/data/schematics/': typeof DataSchematicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/calculator'
    | '/logistics'
    | '/map'
    | '/factories/$factoryId'
    | '/data/'
    | '/factories/'
    | '/data/buildables/$slug'
    | '/data/buildings/$slug'
    | '/data/items/$slug'
    | '/data/recipes/$slug'
    | '/data/schematics/$slug'
    | '/data/buildables/'
    | '/data/buildings/'
    | '/data/items/'
    | '/data/recipes/'
    | '/data/schematics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/logistics'
    | '/map'
    | '/factories/$factoryId'
    | '/data'
    | '/factories'
    | '/data/buildables/$slug'
    | '/data/buildings/$slug'
    | '/data/items/$slug'
    | '/data/recipes/$slug'
    | '/data/schematics/$slug'
    | '/data/buildables'
    | '/data/buildings'
    | '/data/items'
    | '/data/recipes'
    | '/data/schematics'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/calculator'
    | '/logistics'
    | '/map'
    | '/factories/$factoryId'
    | '/data/'
    | '/factories/'
    | '/data/buildables/$slug'
    | '/data/buildings/$slug'
    | '/data/items/$slug'
    | '/data/recipes/$slug'
    | '/data/schematics/$slug'
    | '/data/buildables/'
    | '/data/buildings/'
    | '/data/items/'
    | '/data/recipes/'
    | '/data/schematics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRouteRoute: typeof DataRouteRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  LogisticsRoute: typeof LogisticsRoute
  MapRoute: typeof MapRoute
  FactoriesFactoryIdRoute: typeof FactoriesFactoryIdRoute
  FactoriesIndexRoute: typeof FactoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factories/': {
      id: '/factories/'
      path: '/factories'
      fullPath: '/factories/'
      preLoaderRoute: typeof FactoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/factories/$factoryId': {
      id: '/factories/$factoryId'
      path: '/factories/$factoryId'
      fullPath: '/factories/$factoryId'
      preLoaderRoute: typeof FactoriesFactoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/schematics/': {
      id: '/data/schematics/'
      path: '/schematics'
      fullPath: '/data/schematics/'
      preLoaderRoute: typeof DataSchematicsIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/recipes/': {
      id: '/data/recipes/'
      path: '/recipes'
      fullPath: '/data/recipes/'
      preLoaderRoute: typeof DataRecipesIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/items/': {
      id: '/data/items/'
      path: '/items'
      fullPath: '/data/items/'
      preLoaderRoute: typeof DataItemsIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/buildings/': {
      id: '/data/buildings/'
      path: '/buildings'
      fullPath: '/data/buildings/'
      preLoaderRoute: typeof DataBuildingsIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/buildables/': {
      id: '/data/buildables/'
      path: '/buildables'
      fullPath: '/data/buildables/'
      preLoaderRoute: typeof DataBuildablesIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/schematics/$slug': {
      id: '/data/schematics/$slug'
      path: '/schematics/$slug'
      fullPath: '/data/schematics/$slug'
      preLoaderRoute: typeof DataSchematicsSlugRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/recipes/$slug': {
      id: '/data/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/data/recipes/$slug'
      preLoaderRoute: typeof DataRecipesSlugRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/items/$slug': {
      id: '/data/items/$slug'
      path: '/items/$slug'
      fullPath: '/data/items/$slug'
      preLoaderRoute: typeof DataItemsSlugRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/buildings/$slug': {
      id: '/data/buildings/$slug'
      path: '/buildings/$slug'
      fullPath: '/data/buildings/$slug'
      preLoaderRoute: typeof DataBuildingsSlugRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/buildables/$slug': {
      id: '/data/buildables/$slug'
      path: '/buildables/$slug'
      fullPath: '/data/buildables/$slug'
      preLoaderRoute: typeof DataBuildablesSlugRouteImport
      parentRoute: typeof DataRouteRoute
    }
  }
}

interface DataRouteRouteChildren {
  DataIndexRoute: typeof DataIndexRoute
  DataBuildablesSlugRoute: typeof DataBuildablesSlugRoute
  DataBuildingsSlugRoute: typeof DataBuildingsSlugRoute
  DataItemsSlugRoute: typeof DataItemsSlugRoute
  DataRecipesSlugRoute: typeof DataRecipesSlugRoute
  DataSchematicsSlugRoute: typeof DataSchematicsSlugRoute
  DataBuildablesIndexRoute: typeof DataBuildablesIndexRoute
  DataBuildingsIndexRoute: typeof DataBuildingsIndexRoute
  DataItemsIndexRoute: typeof DataItemsIndexRoute
  DataRecipesIndexRoute: typeof DataRecipesIndexRoute
  DataSchematicsIndexRoute: typeof DataSchematicsIndexRoute
}

const DataRouteRouteChildren: DataRouteRouteChildren = {
  DataIndexRoute: DataIndexRoute,
  DataBuildablesSlugRoute: DataBuildablesSlugRoute,
  DataBuildingsSlugRoute: DataBuildingsSlugRoute,
  DataItemsSlugRoute: DataItemsSlugRoute,
  DataRecipesSlugRoute: DataRecipesSlugRoute,
  DataSchematicsSlugRoute: DataSchematicsSlugRoute,
  DataBuildablesIndexRoute: DataBuildablesIndexRoute,
  DataBuildingsIndexRoute: DataBuildingsIndexRoute,
  DataItemsIndexRoute: DataItemsIndexRoute,
  DataRecipesIndexRoute: DataRecipesIndexRoute,
  DataSchematicsIndexRoute: DataSchematicsIndexRoute,
}

const DataRouteRouteWithChildren = DataRouteRoute._addFileChildren(
  DataRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRouteRoute: DataRouteRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  LogisticsRoute: LogisticsRoute,
  MapRoute: MapRoute,
  FactoriesFactoryIdRoute: FactoriesFactoryIdRoute,
  FactoriesIndexRoute: FactoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
